version: 2
updates:
  # Python dependencies
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "sunday"
      time: "03:00"
      timezone: "UTC"
    open-pull-requests-limit: 5
    target-branch: "develop"
    reviewers:
      - "Fristali"
    assignees:
      - "Fristali"
    labels:
      - "dependencies"
      - "python"
    commit-message:
      prefix: "deps"
      include: "scope"
    ignore:
      # Ignore major version updates for core packages to prevent breaking changes
      - dependency-name: "elasticsearch"
        update-types: ["version-update:semver-major"]
      - dependency-name: "pysigma"
        update-types: ["version-update:semver-major"]
      - dependency-name: "pytest"
        update-types: ["version-update:semver-major"]
    groups:
      # Group related dependencies together
      testing:
        patterns:
          - "pytest*"
          - "coverage"
      linting:
        patterns:
          - "black"
          - "flake8"
          - "isort"
          - "pycodestyle"
          - "pyflakes"
          - "mccabe"
      sigma:
        patterns:
          - "pysigma*"
          - "pyparsing"
      http:
        patterns:
          - "requests"
          - "urllib3"
          - "certifi"
          - "charset-normalizer"
          - "idna"

  # GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "sunday"
      time: "04:00"
      timezone: "UTC"
    open-pull-requests-limit: 3
    target-branch: "develop"
    reviewers:
      - "Fristali"
    assignees:
      - "Fristali"
    labels:
      - "dependencies"
      - "github-actions"
    commit-message:
      prefix: "ci"
      include: "scope"

  # Docker dependencies (if any Docker files are added)
  - package-ecosystem: "docker"
    directory: "/docker"
    schedule:
      interval: "weekly"
      day: "sunday"
      time: "05:00"
      timezone: "UTC"
    open-pull-requests-limit: 2
    target-branch: "develop"
    reviewers:
      - "Fristali"
    assignees:
      - "Fristali"
    labels:
      - "dependencies"
      - "docker"
    commit-message:
      prefix: "docker"
      include: "scope" 