services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:${ELASTIC_VERSION:-8.13.4}
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
      - cluster.name=${ELASTIC_CLUSTER_NAME:-lolbin-cluster}
      - node.name=es01
      - xpack.security.enabled=${ELASTIC_SECURITY_ENABLED:-false}
      - xpack.security.transport.ssl.enabled=${ELASTIC_TLS_ENABLED:-false}
      - xpack.security.http.ssl.enabled=${ELASTIC_TLS_ENABLED:-false}
      - ELASTIC_PASSWORD=${ELASTIC_PASSWORD:-changeme}
      - ES_JAVA_OPTS=${ES_JAVA_OPTS:--Xms512m -Xmx512m}
      - bootstrap.memory_lock=true
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - elasticsearch_data:/usr/share/elasticsearch/data
      - ${ELASTIC_CERT_PATH:-./certs}:/usr/share/elasticsearch/config/certs:ro
    ports:
      - "9200:9200"
      - "9300:9300"
    networks:
      - elastic
    healthcheck:
      test: ["CMD-SHELL", "curl -s http://localhost:9200/_cluster/health | grep -q '\"status\":\"\\(green\\|yellow\\)'"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 30s

  kibana:
    image: docker.elastic.co/kibana/kibana:${ELASTIC_VERSION:-8.13.4}
    container_name: kibana
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
      - ELASTICSEARCH_USERNAME=${ELASTIC_USERNAME:-elastic}
      - ELASTICSEARCH_PASSWORD=${ELASTIC_PASSWORD:-changeme}
      - xpack.security.enabled=${KIBANA_SECURITY_ENABLED:-false}
      - xpack.encryptedSavedObjects.encryptionKey=${KIBANA_ENCRYPTION_KEY:-your_32_character_encryption_key}
      - SERVER_NAME=kibana
      - SERVER_HOST=0.0.0.0
    volumes:
      - kibana_data:/usr/share/kibana/data
      - ${ELASTIC_CERT_PATH:-./certs}:/usr/share/kibana/config/certs:ro
    ports:
      - "5601:5601"
    networks:
      - elastic
    depends_on:
      elasticsearch:
        condition: service_healthy
    healthcheck:
      test: ["CMD-SHELL", "curl -s http://localhost:5601/api/status | grep -q '\"overall\":{\"level\":\"available\"'"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 30s

  logstash:
    image: docker.elastic.co/logstash/logstash:${ELASTIC_VERSION:-8.13.4}
    container_name: logstash
    environment:
      - LS_JAVA_OPTS=${LS_JAVA_OPTS:--Xms512m -Xmx512m}
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
      - ELASTICSEARCH_USERNAME=${ELASTIC_USERNAME:-elastic}
      - ELASTICSEARCH_PASSWORD=${ELASTIC_PASSWORD:-changeme}
      - xpack.monitoring.enabled=${LOGSTASH_MONITORING_ENABLED:-false}
    volumes:
      - ./logstash.conf:/usr/share/logstash/pipeline/logstash.conf:ro
      - ./logstash.yml:/usr/share/logstash/config/logstash.yml:ro
      - ../logs:/usr/share/logstash/logs:ro
      - ${ELASTIC_CERT_PATH:-./certs}:/usr/share/logstash/config/certs:ro
    ports:
      - "5044:5044"
      - "9600:9600"
    networks:
      - elastic
    depends_on:
      elasticsearch:
        condition: service_healthy
    healthcheck:
      test: ["CMD-SHELL", "curl -s http://localhost:9600/_node/stats | grep -q '\"status\":\"green\"'"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 30s

  filebeat:
    image: docker.elastic.co/beats/filebeat:${ELASTIC_VERSION:-8.13.4}
    container_name: filebeat
    user: root
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
      - ELASTICSEARCH_USERNAME=${ELASTIC_USERNAME:-elastic}
      - ELASTICSEARCH_PASSWORD=${ELASTIC_PASSWORD:-changeme}
      - KIBANA_HOST=kibana:5601
    volumes:
      - ./filebeat.yml:/usr/share/filebeat/filebeat.yml:ro
      - ../logs:/var/log/lolbin:ro
      - ${ELASTIC_CERT_PATH:-./certs}:/usr/share/filebeat/config/certs:ro
      - filebeat_data:/usr/share/filebeat/data
      - /var/lib/docker/containers:/var/lib/docker/containers:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
    networks:
      - elastic
    depends_on:
      elasticsearch:
        condition: service_healthy
    command: filebeat -e -strict.perms=false
    healthcheck:
      test: ["CMD-SHELL", "filebeat test output"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s

networks:
  elastic:
    driver: bridge

volumes:
  elasticsearch_data:
    driver: local
  kibana_data:
    driver: local
  filebeat_data:
    driver: local 