name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install test tooling
        run: |
          python -m pip install --upgrade pip
          # pytest for the harness, sigmatools brings the `sigmac` CLI
          pip install pytest sigmatools

      - name: Run tests
        run: make test-rules
